FROM node:22-slim

RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate
RUN npm run build

EXPOSE 8080

# Este comando ejecuta el servidor web (server-baileys.cjs) Y el bot (dist/index.js)
# El servidor web usará CommonJS porque su extensión es .cjs, y el bot usará ESM
CMD ["sh", "-c", "node server-baileys.cjs & node dist/index.js"]