FROM node:22-slim

RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate
RUN npm run build

EXPOSE 8080

# --- NUEVO: Copiamos el script de inicio y le damos permisos ---
COPY start.sh ./
RUN chmod +x start.sh

# --- NUEVO: Usamos el script en lugar del comando directo ---
CMD ["/bin/bash", "start.sh"]